# Application Configuration Properties
spring.application.name=Quantity Measurement App
server.port=8080

# Repository Type Configuration either "cache" or "database"
repository.type=database

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# H2 Database (Development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Logging Configuration
logging.level.root=INFO

# Enable request details logging
spring.mvc.log-request-details=false

# Enable resolved exception logging
spring.mvc.log-resolved-exception=false

# Logging levels
logging.level.org.springframework=WARN
logging.level.org.springframework.web=OFF
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# Your application logging
logging.level.com.app.quantitymeasurementapp=INFO

# DevTools
spring.devtools.add-properties=false

# Custom log pattern for console output to include timestamp, logger name, and message
# The pattern includes:
# %d{yyyy-MM-dd HH:mm:ss} - Timestamp in the format of year-month-day hour:minute:second
# %logger{36} - Logger name truncated to 36 characters
# %line - Line number where the log statement was issued
# %msg%n - The log message followed by a new line
# console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%line] %msg%n"
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{5}:%line - %msg%n

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
